#! /bin/bash

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

apt-get update -y 

apt-get update 

apt-get update --allow-releaseinfo-change && apt-get upgrade -y && apt-get update

apt-get install -y wget curl htop git jq python3 python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools xvfb gnupg 

wget https://raw.githubusercontent.com/t3rs3r4h/master/main/swap4gb

chmod +x swap4gb

./swap4gb

apt-get install -y 

apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils tigervnc-standalone-server tigervnc-common

apt-get install -y xrdp ssl-cert ufw

ufw allow 3389

systemctl set-default graphical.target

apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

dpkg -i google-chrome*.deb

apt-get install -y -f

echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list

wget -q -O- http://www.webmin.com/jcameron-key.asc | apt-key add && apt-get update && apt-get install apt-transport-https -y

curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

apt-get install -y nodejs

apt-get install -y webmin

git clone https://github.com/pyenv/pyenv.git ~/.pyenv

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc

echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc

echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init -)"\nfi' >> ~/.bashrc

exec "$SHELL"

pyenv install 3.9.7

pyenv global 3.9.7

pip install -U playwright pytest-playwright httpx httpx[cli] httpx[http2] httpx[brotli] httpx[socks] beautifulsoup4 fastapi uvicorn[standard] SQLAlchemy pydantic pandas lxml

playwright install

reboot

