#! /bin/bash

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

apt-get update -y 

apt-get update 

apt-get update --allow-releaseinfo-change && apt-get upgrade -y && apt-get update

wget https://raw.githubusercontent.com/t3rs3r4h/master/main/swap2gb

chmod +x swap2gb

./swap2gb

apt-get install -y curl htop 

apt-get install -y jq python3 python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools xvfb

apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils tigervnc-standalone-server tigervnc-common

apt-get install -y xrdp ssl-cert ufw

ufw allow 3389

systemctl set-default graphical.target

pip3 install selenium webdriver-manager undetected-chromedriver requests pyvirtualdisplay

pip3 install -U selenium webdriver-manager undetected-chromedriver requests pyvirtualdisplay

systemctl restart xrdp

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

dpkg -i google-chrome*.deb

apt-get install -y -f

reboot

