#!/bin/bash

#NOTE this setting only for elementaryOS 6.1 and run installer only username root

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

apt-get update

apt-get update -y

apt-get update --allow-releaseinfo-change 

apt-get upgrade -y 

apt-get update

apt-get install -y wget curl htop git jq

apt-get install -y python3.9

apt-get install -y python3-pip

apt-get install -y python3-dev

apt-get install -y python3-setuptools

apt-get install -y python3-openssl

apt-get install -y build-essential

apt-get install -y minicom

apt-get install -y screen

apt-get install -y software-properties-common

curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

apt-get install -y nodejs

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

dpkg -i google-chrome*.deb

apt-get install -y -f

rm -rf google-chrome*.deb

wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -

add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

apt-get update

apt-get install code -y

ln -s python3.9 /usr/bin/python

add-apt-repository ppa:ubuntuhandbook1/app

apt-get update

apt-get install -y libreoffice

apt-get install -y gammu

apt-get install -y gammu-smsd

sed -i 's|${CMAKE_INSTALL_FULL_BINDIR}|/usr/bin|g' /lib/systemd/system/gammu-smsd.service

apt-get install -y gammu-smsd

apt-get install -y libgammu-dev

apt-get install -y audacious

apt-get install -y audacious-plugins

apt-get install -y vlc

apt-get install -y nvidia-driver-510

apt-get install -y nvidia-dkms-510

apt-get install -y nvidia-utils-510

apt-get autoremove -y

clear

pip install python-gammu selenium undetected-chromedriver requests requests[socks] pyserial

prime-select nvidia

reboot
