#!/bin/bash

#NOTE this setting only for elementaryOS 6.1 and run installer only username root
#Kernel 5.11.43
sudo ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

sudo apt-get update

sudo apt-get upgrade -y

sudo apt-get install -y wget curl htop git jq

sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

git clone https://github.com/pyenv/pyenv.git ~/.pyenv

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc

echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc

echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init -)"\nfi' >> ~/.bashrc

sudo apt-get install -y python3-dev python3-setuptools python3-openssl build-essential minicom screen software-properties-common

sudo curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

sudo apt-get install -y nodejs

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo dpkg -i google-chrome*.deb

sudo apt-get install -y -f

rm -rf google-chrome*.deb

sudo wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

sudo add-apt-repository ppa:ubuntuhandbook1/app

sudo apt-get update

sudo apt-get install -y code nodejs

sudo add-apt-repository ppa:ubuntuhandbook1/appapt-get install -y libreoffice

sudo apt-get install -y gammu gammu-smsd libgammu-dev libgammu8 libgammu-i18n

#sed -i 's|${CMAKE_INSTALL_FULL_BINDIR}|/usr/bin|g' /lib/systemd/system/gammu-smsd.service
#apt-get install -y gammu gammu-smsd libgammu-dev libgammu8 libgammu-i18n

sudo apt-get install -y audacious audacious-plugins vlc

sudo apt-get autoremove -y

clear

source ~/.bashrc

pyenv install 3.10.4

pyenv global 3.10.4

pip install python-gammu selenium undetected-chromedriver requests requests[socks] pyserial

reboot
