#!/bin/bash

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

apt-get update -y 

apt-get update

apt-get update --allow-releaseinfo-change && apt-get upgrade -y && apt-get update

apt-get install -y wget curl htop git jq python3.9 python3-pip python3-dev build-essential python3-setuptools python3-openssl minicom screen software-properties-common

curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

apt-get install -y nodejs

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

dpkg -i google-chrome*.deb

apt-get install -y -f

rm -rf google-chrome*.deb

wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -

add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

apt-get update && apt-get install code -y

ln -s python3.9 /usr/bin/python

add-apt-repository ppa:forkotov02/ppa

apt-get install libreoffice gammu gammu-smsd libgammu-dev qmmp qmmp-plugin-pack libtag1-vanilla vlc -y

clear

pip install python-gammu selenium undetected-chromedriver requests requests[socks] pyserial

python -V && pip -V
