#!/bin/bash


apt-get install -y wget curl htop git jq python3 python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
echo 'eval "$(pyenv init -)"' >> ~/.profile

exec "$SHELL"

pyenv install 3.9.7

pyenv global 3.9.7

curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

apt-get install -y nodejs

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

dpkg -i google-chrome*.deb

apt-get install -y -f

rm -rf google-chrome*.deb

apt-get install minicom screen -y

wget –q https://packages.microsoft.com/key/microsoft.asc -O- | sudo apt-key add -

add-apt-repository “deb[arch=amd64] https://packages.microsoft.com/repos/vscode stable main”

apt-get update && apt-get install code -y
