#! /bin/sh
apt-get update -y
apt-get install iproute2 -y
myIP=$(ip addr | grep -Po '(?!(inet 127.\d.\d.1))(inet \K(\d{1,3}\.){3}\d{1,3})')
echo "ok.. please wait a few minute!"
sleep 3
sudo apt-get update -y
sudo apt-get install make gcc -y
sudo apt-get install mc -y
sudo apt-get install curl -y
sudo apt-get install build-essential -y
sudo wget https://www.inet.no/dante/files/dante-1.4.3.tar.gz
sudo gunzip dante-1.4.3.tar.gz
sudo tar -xf dante-1.4.3.tar
cd dante-1.4.3/
sudo ./configure
sudo make
sudo make install
sudo bash -c "cat <<EOF > /etc/danted.conf
logoutput: syslog
internal: $myIP port = 1990
external: $myIP
external.rotation: same-same
method: username none
user.privileged: proxy
user.notprivileged: nobody
client pass {
        from: 0.0.0.0/0 port 1-65535 to: 0.0.0.0/0
}
client block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
}
pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        protocol: tcp udp
}
block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
}
EOF"

sudo bash -c "cat <<EOF > /etc/sockd.sh
#! /bin/sh
sudo /usr/local/sbin/sockd -D -N 2 -f /etc/danted.conf
EOF"

sudo chmod +x /etc/sockd.sh

sudo crontab -l | { cat; echo '@reboot /etc/sockd.sh'; } | crontab -

sudo /usr/local/sbin/sockd -D -N 2 -f /etc/danted.conf

tail /var/log/syslog

echo "your socks5 is: $(curl -s ifconfig.me):1990"
