#! /bin/sh
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
apt-get update -y
apt-get update
apt-get update --allow-releaseinfo-change && apt-get upgrade -y && apt-get update
wget https://raw.githubusercontent.com/ontoseno90/master/main/swap2gb
chmod +x swap2gb && ./swap2gb
apt-get install iproute2 -y
myIP=$(ip addr | grep -Po '(?!(inet 127.\d.\d.1))(inet \K(\d{1,3}\.){3}\d{1,3})')
echo "ok.. please wait a few minute!"
sleep 3
apt-get update -y
apt-get install make gcc -y
apt-get install mc -y
apt-get install curl -y
apt-get install build-essential -y
wget https://www.inet.no/dante/files/dante-1.4.3.tar.gz
gunzip dante-1.4.3.tar.gz
tar -xf dante-1.4.3.tar
cd dante-1.4.3/
./configure
make
make install
bash -c "cat <<EOF > /etc/danted.conf
logoutput: syslog
internal: $myIP port = 1990
external: $myIP
external.rotation: same-same
method: username none
user.privileged: proxy
user.notprivileged: nobody
client pass {
        from: 0/0 port 1-65535 to: 0/0
}
client block { 
        from: 0/0 to: 0/0
}
pass {
        from: 0/0 to: 0/0
        protocol: tcp udp
}
block {
        from: 0/0 to: 0/0
}
EOF"

bash -c "cat <<EOF > /etc/sockd.sh
#! /bin/sh
/usr/local/sbin/sockd -D -N 2 -f /etc/danted.conf
EOF"

chmod +x /etc/sockd.sh

crontab -l | { cat; echo '@reboot /etc/sockd.sh'; } | crontab -

/usr/local/sbin/sockd -D -N 2 -f /etc/danted.conf

tail /var/log/syslog

echo "your socks5 is: $(curl -s ifconfig.me):1990"

reboot
